-- Encrypted Circle events (Phase 2): arriving at or leaving a place, and
-- journey updates ("Walk me home started / arrived").
--
-- Events are sealed with the sender's *location* key (D7), so only members
-- who may see the sender's live location can read them; SOS-only viewers
-- get nothing. The event type lives inside the ciphertext: the server only
-- learns that a member posted something, not whether they arrived home.
-- Places themselves never leave the phone (see docs/architecture.md §4.6).

create table public.circle_events (
  id uuid primary key,  -- generated by the app, so retries are idempotent
  circle_id uuid not null,
  sender_id uuid not null,
  sender_device_id uuid not null references public.devices (id) on delete cascade,
  key_version integer not null check (key_version >= 1),
  ciphertext text not null check (char_length(ciphertext) <= 1024),
  created_at timestamptz not null default now(),
  foreign key (circle_id, sender_id)
    references public.circle_members (circle_id, user_id) on delete cascade
);

create index circle_events_circle on public.circle_events (circle_id, created_at desc);

alter table public.circle_events enable row level security;
revoke all on table public.circle_events from authenticated;
grant select, insert, delete on table public.circle_events to authenticated;

create policy circle_events_select_member on public.circle_events
  for select to authenticated using (private.is_circle_member(circle_id));

-- Same rule as location writes: from your own active device, in a Circle
-- where you haven't paused. An event says where you are, so pausing must
-- stop it too.
create policy circle_events_insert_own on public.circle_events
  for insert to authenticated
  with check (private.can_write_location(circle_id, sender_id, sender_device_id));

create policy circle_events_delete_own on public.circle_events
  for delete to authenticated using (sender_id = (select auth.uid()));

create function private.rate_limit_circle_events()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hit_rate_limit('circle_event', 120, interval '1 hour');
  return new;
end;
$$;

create trigger circle_events_rate_limit before insert on public.circle_events
  for each row execute function private.rate_limit_circle_events();

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.circle_events;
  end if;
end;
$$;
