-- Check-in timer and "Walk me home" (Phase 2).
--
-- The deadline lives on the server so that a phone that is switched off,
-- broken or taken still triggers help. When starting, the phone also
-- uploads one *escrowed alert* per Circle: an ordinary E2EE alert payload,
-- sealed with its alert key, that the server can't read. If the deadline
-- passes without a check-in, the watchdog copies each escrow into
-- public.alerts unchanged, and members' apps open it like an SOS.
--
-- The server learns that a timer exists and when it ends, never where the
-- user is or is going.

create table public.checkins (
  id uuid primary key,  -- generated by the app
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  kind text not null check (kind in ('timer', 'journey')),
  deadline timestamptz not null,
  status text not null default 'active'
    check (status in ('active', 'completed', 'cancelled', 'missed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  missed_at timestamptz,
  check (deadline > created_at and deadline <= created_at + interval '24 hours')
);

create index checkins_due on public.checkins (deadline) where status = 'active';
create index checkins_user on public.checkins (user_id, created_at desc);

alter table public.checkins enable row level security;
revoke all on table public.checkins from authenticated;
-- Inserts may only choose the id, kind and deadline; owner, status and
-- timestamps come from the defaults.
grant select on table public.checkins to authenticated;
grant insert (id, kind, deadline) on table public.checkins to authenticated;
-- Only these columns can change, and only while the check-in is active:
-- the owner checks in, cancels or extends. Nobody can set 'missed' except
-- the watchdog, and a missed check-in can't be quietly undone.
grant update (status, deadline) on table public.checkins to authenticated;

create policy checkins_select_own on public.checkins
  for select to authenticated using (user_id = (select auth.uid()));
create policy checkins_insert_own on public.checkins
  for insert to authenticated
  with check (user_id = (select auth.uid()) and status = 'active' and missed_at is null);
create policy checkins_update_own on public.checkins
  for update to authenticated
  using (user_id = (select auth.uid()) and status = 'active')
  with check (
    user_id = (select auth.uid())
    and status in ('active', 'completed', 'cancelled')
    -- Extending must move the deadline into the future; checking in or
    -- cancelling is always allowed, even in the last seconds.
    and (status <> 'active' or deadline > now())
  );

create trigger checkins_updated_at before update on public.checkins
  for each row execute function private.set_updated_at();

create function private.checkin_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hit_rate_limit('checkin', 30, interval '1 hour');
  return new;
end;
$$;

create trigger checkins_rate_limit before insert on public.checkins
  for each row execute function private.checkin_rate_limit();

create function private.is_my_active_checkin(p_checkin uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.checkins c
    where c.id = p_checkin and c.user_id = auth.uid() and c.status = 'active'
  );
$$;

-- One escrowed alert per Circle. The phone refreshes the ciphertext with
-- its latest location while the timer runs.
create table public.checkin_escrows (
  checkin_id uuid not null references public.checkins (id) on delete cascade,
  circle_id uuid not null,
  user_id uuid not null default auth.uid(),
  alert_id uuid not null unique,
  sender_device_id uuid not null references public.devices (id) on delete cascade,
  key_version integer not null check (key_version >= 1),
  ciphertext text not null check (char_length(ciphertext) <= 1024),
  updated_at timestamptz not null default now(),
  primary key (checkin_id, circle_id),
  foreign key (circle_id, user_id)
    references public.circle_members (circle_id, user_id) on delete cascade
);

alter table public.checkin_escrows enable row level security;
revoke all on table public.checkin_escrows from authenticated;
grant select, delete on table public.checkin_escrows to authenticated;
grant insert (checkin_id, circle_id, alert_id, sender_device_id, key_version, ciphertext)
  on table public.checkin_escrows to authenticated;
grant update (sender_device_id, key_version, ciphertext) on table public.checkin_escrows to authenticated;

create policy escrows_select_own on public.checkin_escrows
  for select to authenticated using (user_id = (select auth.uid()));
create policy escrows_insert_own on public.checkin_escrows
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and private.is_my_active_checkin(checkin_id)
    and private.is_my_active_device(sender_device_id)
    and private.is_circle_member(circle_id)
  );
create policy escrows_update_own on public.checkin_escrows
  for update to authenticated
  using (user_id = (select auth.uid()) and private.is_my_active_checkin(checkin_id))
  with check (
    user_id = (select auth.uid())
    and private.is_my_active_checkin(checkin_id)
    and private.is_my_active_device(sender_device_id)
  );
create policy escrows_delete_own on public.checkin_escrows
  for delete to authenticated using (user_id = (select auth.uid()));

create trigger checkin_escrows_updated_at before update on public.checkin_escrows
  for each row execute function private.set_updated_at();

-- Missed check-ins arrive as alerts of their own kind.
alter table public.alerts drop constraint alerts_kind_check;
alter table public.alerts add constraint alerts_kind_check
  check (kind in ('panic', 'checkin_missed'));

-- The alert rate limit counts per user; the watchdog runs as no user at
-- all (pg_cron), and must never be blocked by it.
create or replace function private.rate_limit_alerts()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is not null then
    perform private.hit_rate_limit('panic_alert', 30, interval '1 hour');
  end if;
  return new;
end;
$$;

-- The watchdog: marks overdue check-ins as missed and releases their
-- escrowed alerts. Run every minute by pg_cron (next migration). Escrows
-- for Circles the user has since left, or from a revoked device, are not
-- released. Returns the number of alerts released.
create function private.expire_checkins()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_released integer;
begin
  with due as (
    update public.checkins
       set status = 'missed', missed_at = now()
     where status = 'active' and deadline <= now()
    returning id, user_id
  ), released as (
    insert into public.alerts
      (id, incident_id, circle_id, sender_id, sender_device_id, kind, key_version, ciphertext)
    select e.alert_id, d.id, e.circle_id, d.user_id, e.sender_device_id,
           'checkin_missed', e.key_version, e.ciphertext
      from due d
      join public.checkin_escrows e on e.checkin_id = d.id
      join public.circle_members m on m.circle_id = e.circle_id and m.user_id = d.user_id
      join public.devices dv on dv.id = e.sender_device_id and dv.revoked_at is null
    on conflict (id) do nothing
    returning 1
  )
  select count(*) into v_released from released;
  return v_released;
end;
$$;

revoke execute on function private.expire_checkins() from public, anon, authenticated;

grant execute on function
  private.is_my_active_checkin(uuid)
to authenticated;

-- The owner's app learns from Realtime that a check-in was missed.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.checkins;
  end if;
end;
$$;
